
import React, { useState } from 'react';
import { Sparkles, Loader2, Wand2, ArrowRight } from 'lucide-react';
import { getBeautyConsultation } from '../geminiService';

export const AIConsultant: React.FC = () => {
  const [skinType, setSkinType] = useState('Normal');
  const [concerns, setConcerns] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    const data = await getBeautyConsultation(skinType, concerns);
    setResult(data);
    setLoading(false);
  };

  return (
    <div className="max-w-4xl mx-auto px-4 py-20">
      <div className="text-center mb-16 space-y-4">
        <div className="inline-block p-3 bg-gold/10 rounded-full text-gold mb-2">
          <Sparkles size={32} />
        </div>
        <h1 className="text-4xl font-serif">AI Beauty Curator</h1>
        <p className="text-slate-500 italic font-light">
          Experience a personalized skincare and makeup blueprint generated by our intelligent curation engine.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-5 gap-12">
        <div className="md:col-span-2 space-y-8 bg-white p-8 border border-slate-100 shadow-sm">
          <form onSubmit={handleSubmit} className="space-y-6">
            <div>
              <label className="block text-xs font-bold tracking-widest uppercase mb-2">Skin Type</label>
              <select
                value={skinType}
                onChange={(e) => setSkinType(e.target.value)}
                className="w-full border-b border-slate-200 py-2 text-sm focus:border-gold outline-none transition-colors"
              >
                <option>Normal</option>
                <option>Dry</option>
                <option>Oily</option>
                <option>Combination</option>
                <option>Sensitive</option>
              </select>
            </div>
            <div>
              <label className="block text-xs font-bold tracking-widest uppercase mb-2">Primary Concerns</label>
              <textarea
                value={concerns}
                onChange={(e) => setConcerns(e.target.value)}
                placeholder="e.g. Fine lines, dehydration, redness..."
                className="w-full border border-slate-200 p-4 text-sm focus:border-gold outline-none h-32 resize-none transition-colors"
              />
            </div>
            <button
              disabled={loading}
              className="w-full bg-slate-900 text-white py-4 text-xs font-bold tracking-widest hover:bg-gold flex items-center justify-center gap-2 transition-all"
            >
              {loading ? <Loader2 className="animate-spin" size={16} /> : <Wand2 size={16} />}
              GENERATE ANALYSIS
            </button>
          </form>
        </div>

        <div className="md:col-span-3">
          {!result && !loading && (
            <div className="h-full flex flex-col items-center justify-center border-2 border-dashed border-slate-200 p-12 text-center text-slate-400">
              <Sparkles className="mb-4 opacity-30" size={48} />
              <p className="text-sm italic font-light">Input your details to see our professional recommendations.</p>
            </div>
          )}

          {loading && (
            <div className="h-full flex flex-col items-center justify-center space-y-4">
              <Loader2 className="animate-spin text-gold" size={40} />
              <p className="text-slate-500 text-sm font-light italic">Articulating your personalized blueprint...</p>
            </div>
          )}

          {result && !loading && (
            <div className="space-y-8 animate-in fade-in zoom-in-95 duration-500">
              <div className="bg-slate-50 p-8 border-l-4 border-gold">
                <h3 className="text-xs font-bold tracking-[0.2em] uppercase text-gold mb-4">Recommended Protocol</h3>
                <ul className="space-y-4">
                  {result.routine.map((step: string, idx: number) => (
                    <li key={idx} className="flex gap-4 text-sm font-light text-slate-700">
                      <span className="text-gold font-bold font-serif">{idx + 1}.</span>
                      {step}
                    </li>
                  ))}
                </ul>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                <div className="bg-white p-6 shadow-sm border border-slate-100">
                  <h4 className="text-[10px] font-bold tracking-widest uppercase mb-2 text-slate-400">Recommended Service</h4>
                  <p className="font-serif text-lg text-slate-800">{result.recommendedService}</p>
                </div>
                <div className="bg-white p-6 shadow-sm border border-slate-100">
                  <h4 className="text-[10px] font-bold tracking-widest uppercase mb-2 text-slate-400">Expert Insight</h4>
                  <p className="text-sm font-light italic text-slate-600 leading-relaxed">{result.expertTip}</p>
                </div>
              </div>

              <button
                onClick={() => window.location.href = '#/services'}
                className="w-full flex items-center justify-center gap-2 py-4 border border-slate-900 text-xs font-bold tracking-widest hover:bg-slate-900 hover:text-white transition-all"
              >
                EXPLORE ALL SERVICES <ArrowRight size={14} />
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
